localised-values:
  SECRET_KEY: ${SECRET_KEY}
server:
  port: 8080
  ssl:
    key-store: ./keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: selfsigned_localhost_sslserver
spring:
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    database: POSTGRESQL
pps-app:
  jwt:
    cookieName: jwt
    dayCountOfAuthValitiy: 1
    