localised-values:
  SECRET_KEY: ${SECRET_KEY}
  CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}

spring:
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    database: POSTGRESQL
pps-app:
  jwt:
    cookieName: jwt
    dayCountOfAuthValitiy: 1

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
  ssl:
    key-store: ./keystore.p12
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: selfsigned_localhost_sslserver

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080