name: build-on-merge-action
run-name: ${{ github.actor }} is build-backend-action
on:
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: apiuser
          POSTGRES_PASSWORD: cV87SuX&3gbdYJD8n*A4OfHy8Hv@l1y
          POSTGRES_DB: PERSONAL_PLUG_DB
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8100:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install
    - name: Build Docker image
      run: docker build -t personal-plug-site .
    - name: Run Docker container
      run: docker run -d -p 8080:8080 personal-plug-site
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/personal-plug-site:latest